name: Go

on: [push, pull_request]
jobs:
  Linux:
    strategy:
      matrix:
        go-version: [1.19.x]
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/cache@v3
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: ${{ runner.os }}-go-
    - uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}
    - uses: actions/checkout@v3

    - name: Verify dependencies
      run: go mod verify

    - name: Create build directory
      run: mkdir build

    - name: Build
      run: go build -o ./build/${{ runner.os }}-server .

    - name: Run go vet
      run: go vet .

    - name: Run tests
      run: go test -race -vet=off ./...

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: Releases
        path: ./build/${{ runner.os }}-server
  Windows:
    strategy:
      matrix:
        go-version: [ 1.19.x ]
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - uses: actions/checkout@v3

      - name: Verify dependencies
        run: go mod verify

      - name: Create build directory
        run: mkdir build

      - name: Build
        run: go build -o ./build/${{ runner.os }}-server.exe .

      - name: Run go vet
        run: go vet .

      - name: Run tests
        run: go test -race -vet=off ./...

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Releases
          path: ./build/${{ runner.os }}-server.exe
  Graph:
    strategy:
      matrix:
        go-version: [ 1.19.x ]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - uses: actions/checkout@v3

      - name: Install godegraph
        run: go install github.com/kisielk/godepgraph

      - name: Update apt-get
        run: sudo apt-get update

      - name: Install dot
        run: sudo apt-get install graphviz

      - name: Generate graph
        run: godepgraph kamigen/socket | dot -Tpng -o godepgraph.png

      - name: Upload graph
        uses: actions/upload-artifact@v3
        with:
          name: godepgraph.png
          path: ./godepgraph.png