name: Go

on: [push, pull_request]
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.19.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/cache@v3
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: ${{ runner.os }}-go-
    - uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}
    - uses: actions/checkout@v3

    - name: Verify dependencies
      run: go mod verify

    - name: Build
      run: go build .

    - name: Run go vet
      run: go vet .

    - name: Run tests
      run: go test -race -vet=off ./...
      
    - name: Create directory
      run: mkdir -p ./artifact

    - name: Insert compiled
      run: cat ./socket > ./artifact/server

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: server
        path: ./artifact/server
